AU:
  AU12:
    features:
    - - OutlineRight_Mouth
      - OutlineRight_Cheek
    - - OutlineRight_Mouth
      - UpperLip_Center
    - - UpperLip_Center
      - LowerLip_Center
    ratios:
    - - - OutlineRight_Mouth
        - UpperLip_Center
      - - UpperLip_Center
        - LowerLip_Center
  AU18:
    features:
    - - OutlineRight_Mouth
      - UpperLip_Center
    - - UpperLip_Center
      - LowerLip_Center
    - - OutlineRight_Mouth
      - LowerLip_Center
    ratios:
    - - - OutlineRight_Mouth
        - UpperLip_Center
      - - UpperLip_Center
        - LowerLip_Center
  AU1_2:
    features:
    - - OutlineRight_Indent
      - ' RightBrow_Outer'
    - - NostrilsTop_Centre
      - Brow_MidPoint
  AU25_26:
    features:
    - - UpperLip_Center
      - LowerLip_Center
  AU41:
    features:
    - - Brow_MidPoint
      - NostrilsTop_Centre
  AU43_45:
    features:
    - - RightEye_Top
      - RightEye_Bottom
    ratios:
    - - - RightEye_Top
        - RightEye_Bottom
      - - RightEye_Inner
        - RightEye_Outer
  AU6:
    features:
    - - OutlineRight_Cheek
      - OutlineRight_Indent
    - - OutlineRight_Cheek
      - OutlineRight_Brow
  AU9_10:
    features:
    - - NostrilsTop_Centre
      - RightNostrils_Top
    - - RightNostrils_Top
      - RightNostrils_Bottom
    - - RightNostrils_Tip
      - RightNostrils_Bottom
    - - RightNostrils_Tip
      - RightNostrils_Top
EXPERIMENTER: reza
PROJECT_NAME: macaque_face_v2
fps: 30.0
project_path: C:\Users\hseyed\Documents\Python\Monkey_face_Self\AU_analysis
target_code: 40
window_sec: 1.5
baseline_window: 0.5
